echo "<html>"
echo "<center>"
echo "<br>"
echo "<h1>Frontend</h1>"
echo "<br>"
echo "DATE:"`date`
echo "<br>"
echo "BUILD: `echo $BUILD_NUMBER`"
echo "<br>"
echo "JOB: `echo $JOB_NAME`"
echo "</center>"
echo "</html>"
